# Generated by Django 3.0.6 on 2020-05-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('des_id', models.IntegerField(primary_key=True, serialize=False)),
                ('des_nom', models.CharField(max_length=60)),
                ('des_ape', models.CharField(max_length=60)),
                ('des_tel', models.CharField(max_length=60)),
                ('des_email', models.CharField(max_length=90)),
            ],
        ),
    ]
