# Generated by Django 3.0.6 on 2020-05-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('jue_id', models.IntegerField(primary_key=True, serialize=False)),
                ('jue_nom', models.CharField(max_length=60)),
                ('jue_val', models.IntegerField()),
                ('jue_des', models.CharField(max_length=250)),
            ],
        ),
    ]
